site_name: Valoria Wiki
site_description: Вики приватного Minecraft-сервера Valoria

theme:
  name: material
  language: ru
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Светлая тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Тёмная тема
  features:
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/GKBgTjb7cX
    - icon: fontawesome/brands/telegram
      link: https://t.me/Valoria_LastTime
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ValoriaProject
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@off.valoria

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang: ru

nav:
  - Главная: index.md
  - Информация:
      - Команды: informaciya/komandy.md
      - Фишки сервера:
          - Обзор: informaciya/fishki-servera.md
          - Технологии: informaciya/fishki-servera/tekhnologii.md
          - Кастомные крафты: informaciya/fishki-servera/kastomnye-krafty.md
          - Быстрое опадение листвы: informaciya/fishki-servera/bystroe-opadenie-listvy.md
          - Быстрый бетон: informaciya/fishki-servera/bystryi-beton.md
          - Чат: informaciya/fishki-servera/chat.md
          - Мини-блоки: informaciya/fishki-servera/mini-bloki.md
          - Некопируемые арты и шаблоны: informaciya/fishki-servera/nekopiruemye-arty-i-shablony.md
          - Невидимые рамки: informaciya/fishki-servera/nevidimye-ramki.md
          - PlasmoVoice и EmoteCraft: informaciya/fishki-servera/plasmovoice-i-emotecraft.md
          - Пластинки: informaciya/fishki-servera/plastinki.md
          - Портал любой формы: informaciya/fishki-servera/portal-lyuboi-formy.md
          - Редактирование стоек для брони: informaciya/fishki-servera/redaktirovanie-stoek-dlya-broni.md
          - Скрытые никнеймы: informaciya/fishki-servera/skrytye-nikneimy.md
          - Выпадение голов: informaciya/fishki-servera/vypadenie-golov.md
          - Ограничение элитр: informaciya/fishki-servera/ogranichenie-elitr.md
          - Командная защита: informaciya/fishki-servera/komandnaya-zashita.md
          - Улучшения для счастливых гастов: informaciya/fishki-servera/uluchsheniya-dlya-schastlivykh-gastov.md
          - Алкоголизм: informaciya/fishki-servera/alkogolizm.md
          - Мелкие механики: informaciya/fishki-servera/melkie-mekhaniki.md
  - Прочая информация:
      - Работать с нами: prochaya-informaciya/rabotat-s-nami.md
      - Спонсорство: prochaya-informaciya/sponsorstvo.md
